export const movies = [
  {
    id: 533535,
    title: "Deadpool & Wolverine",
    release_date: "2024-07-24",
    backdrop_path: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    category: "Action",
  },
  {
    id: 718821,
    title: "Twisters",
    release_date: "2024-07-10",
    backdrop_path: "https://image.tmdb.org/t/p/original/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    category: "Thriller",
  },
  {
    id: 1022789,
    title: "Inside Out 2",
    release_date: "2024-06-11",
    backdrop_path: "https://image.tmdb.org/t/p/original/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    category: "Animation",
  },
  {
    id: 519182,
    title: "Despicable Me 4",
    release_date: "2024-06-20",
    backdrop_path: "https://image.tmdb.org/t/p/original/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    category: "Animation",
  },
  {
    id: 573435,
    title: "Bad Boys: Ride or Die",
    release_date: "2024-06-05",
    backdrop_path: "https://image.tmdb.org/t/p/original/3q01ACG0MWm0DekhvkPFCXyPZSu.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/oGythE98MYleE6mZlGs5oBGkux1.jpg",
    category: "Action",
  },
  {
    id: 1160018,
    title: "Kill",
    release_date: "2024-07-03",
    backdrop_path: "https://image.tmdb.org/t/p/original/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/m2zXTuNPkywdYLyWlVyJZW2QOJH.jpg",
    category: "Thriller",
  },
  {
    id: 762441,
    title: "A Quiet Place: Day One",
    release_date: "2024-06-26",
    backdrop_path: "https://image.tmdb.org/t/p/original/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
    category: "Horror",
  },
  {
    id: 831815,
    title: "Bikini: Sandy Movie",
    release_date: "2024-08-01",
    backdrop_path: "https://image.tmdb.org/t/p/original/hdFIdXwS8FSN2wIsuotjW1mshI0.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
    category: "Animation",
  },
  {
    id: 1079091,
    title: "It Ends with Us",
    release_date: "2024-08-07",
    backdrop_path: "https://image.tmdb.org/t/p/original/8yPSYhooj8nyBbmV3GVdLDwuE7e.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
    category: "Drama",
  },
  {
    id: 945961,
    title: "Alien: Romulus",
    release_date: "2024-08-13",
    backdrop_path: "https://image.tmdb.org/t/p/original/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    category: "Sci-Fi",
  },
  {
    id: 155,
    title: "The Dark Knight",
    release_date: "2008-07-18",
    backdrop_path: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    category: "Action",
  },
  {
    id: 424,
    title: "Schindler's List",
    release_date: "1993-11-30",
    backdrop_path: "https://image.tmdb.org/t/p/original/cTNYRUTXkBgPH3wP3kmPUB5U6dA.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    category: "Drama",
  },
  {
    id: 603,
    title: "The Matrix",
    release_date: "1999-03-31",
    backdrop_path: "https://image.tmdb.org/t/p/original/7u3pxc0K1wx32IleAkLv78MKgrw.jpg",
    poster_path: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    category: "Sci-Fi",
  },
  {
    id: 27205,
    title: "Inception",
    release_date: "2010-07-16",
    backdrop_path: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    category: "Thriller",
  },
  {
    id: 122,
    title: "The Lord of the Rings: The Return of the King",
    release_date: "2003-12-01",
    backdrop_path: "https://image.tmdb.org/t/p/original/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    category: "Action",
  },
  {
    id: 278,
    title: "The Shawshank Redemption",
    release_date: "1994-09-23",
    backdrop_path: "https://image.tmdb.org/t/p/original/wPU78OPN4BYEgWYdXyg0phMee64.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    category: "Drama",
  },
  {
    id: 1891,
    title: "The Empire Strikes Back",
    release_date: "1980-05-17",
    backdrop_path: "https://image.tmdb.org/t/p/original/mD8TJu9zjyrg1YBuZbuQ8Kz3Fte.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/7BuH8itoSrLExs2YZSsM01Qk2no.jpg",
    category: "Sci-Fi",
  },
  {
    id: 807,
    title: "Se7en",
    release_date: "1995-09-22",
    backdrop_path: "https://image.tmdb.org/t/p/original/9fZ1gQ47zpk2rXqI6E6Vb26NvD7.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    category: "Thriller",
  },
  {
    id: 460465,
    title: "Mortal Kombat",
    release_date: "2021-04-07",
    backdrop_path: "https://image.tmdb.org/t/p/original/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/xGuOF1T3WmPsAcQEQJfnG7Ud9f8.jpg",
    category: "Action",
  },
  {
    id: 615656,
    title: "Monster Hunter",
    release_date: "2020-12-03",
    backdrop_path: "https://image.tmdb.org/t/p/original/8tNX8s3j1O0eqilOQkuroRLyOZA.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/1UCOF11QCw8kcqvce8LKOO6pimh.jpg",
    category: "Action",
  },
  {
    id: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    release_date: "2023-05-03",
    backdrop_path: "https://image.tmdb.org/t/p/original/h5mDpuA4fFbECd6la3KH5y99Kbc.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    category: "Sci-Fi",
  },
  {
    id: 420818,
    title: "The Lion King",
    release_date: "2019-07-12",
    backdrop_path: "https://image.tmdb.org/t/p/original/nRXO2SnOA75OsWhNhXstHB8ZmI3.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg",
    category: "Animation",
  },
  {
    id: 80321,
    title: "Shutter Island",
    release_date: "2010-02-14",
    backdrop_path: "https://image.tmdb.org/t/p/original/hY8JlVQ8H8FnfXNPghrKlZV5fV7.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
    category: "Thriller",
  },
  {
    id: 138843,
    title: "The Conjuring",
    release_date: "2013-07-18",
    backdrop_path: "https://image.tmdb.org/t/p/original/x4KdvKlt6KKg4piywRmnY8UJ3O1.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    category: "Horror",
  },
  {
    id: 76341,
    title: "Mad Max: Fury Road",
    release_date: "2015-05-13",
    backdrop_path: "https://image.tmdb.org/t/p/original/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    category: "Action",
  },
  {
    id: 11,
    title: "Star Wars: A New Hope",
    release_date: "1977-05-25",
    backdrop_path: "https://image.tmdb.org/t/p/original/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
    poster_path: "https://image.tmdb.org/t/p/original/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    category: "Sci-Fi",
  },
];
